from django.urls import path

from . import views

urlpatterns = [
    path(
        route='',
        view=views.HomeView.as_view(redirect_authenticated_user=True),
        name='home',
    ),
    path(
        route='tickets/',
        view=views.TicketListView.as_view(),
        name='tickets',
    ),
    path(
        route='posts/',
        view=views.TicketListView.as_view(),
        name='posts',
    ),
    path(
        route='add_ticket/',
        view=views.TicketCreateView.as_view(),
        name='add_ticket'
    ),
    path(
        route='add_review/',
        view=views.add_review,
        name='add_review'
    ),
    path(
        route='add_review/<int:id_ticket>/',
        view=views.add_review,
        name='add_review'
    ),
    path(
        route='sub/',
        view=views.sub,
        name='sub'
    ),
    path(
        'update/ticket/<int:pk>/',
        views.TicketUpdateView.as_view(),
        name='update_ticket',
    ),
    path(
        'delete/ticket/<int:pk>/',
        views.TicketDeleteView.as_view(),
        name='delete_ticket',
    ),
    path(
        'update/review/<int:pk>/',
        views.ReviewUpdateView.as_view(),
        name='update_review',
    ),
    path(
        'delete/review/<int:pk>/',
        views.ReviewDeleteView.as_view(),
        name='delete_review',
    ),
]
