# Generated by Django 3.1.7 on 2021-02-26 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_auto_20210226_1324'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ticket2',
        ),
    ]
